name: "Build OneFlow with Conda"
description: ""
inputs:
  env:
    description: "environments to build OneFlow: conda, manylinux"
    required: true
  cmake-init-cache:
    description: "path to CMake initial cache file to build OneFlow"
    required: true
  cuda-version:
    description: "default is none, format: 10.1, 10.2"
    required: false
    default: "none"
  key:
    description: "the key to check if two builds are equivalent to each other, usually is hash value of non-test cpp and python files"
    required: true
    default: "none"
  force-rebuild:
    description: "rebuild even package with same key found"
    required: false
    default: "false"
  conda-env-file:
    description: ""
    required: true
  src:
    description: "src path to OneFlow, default is current directory"
    required: false
    default: "."
  dry-run:
    description: ""
    required: false
    default: "false"
  action:
    description: "internal, current action name"
    required: false
    default: "conda"
outputs:
  pip-index-url:
    description: "pip index url could be use to install oneflow"
runs:
  using: "node12"
  main: "../dist/index.js"
