name: 'Build/Get OneFlow'
description: ''
inputs:
  action-type:
    description: ''
    required: false
    default: 'build-oneflow'
  # OneFlow args
  oneflow-build-env:
    description: 'environment to build OneFlow: conda, manylinux, llvm'
    required: true
  oneflow-src:
    description: 'path to OneFlow source code'
    required: true
  oneflow-build-key:
    description: 'the key to check if two builds are equivalent to each other, usually is hash value of non-test cpp and python files'
    required: true
    default: 'none'
  # TODO: make it optional, build-script can include a cmake-init-cache there is no reuse needed
  # CMake args
  cmake-init-cache:
    description: 'path to CMake initial cache file to build OneFlow'
    required: true
  # Cuda args
  cuda-version:
    description: 'default is none, format: 10.2, 11.2'
    required: false
  compute-platform:
    description: 'default is none, format: cpu, cu112, cu102'
    required: false
  # Conda args
  conda-env-file:
    description: 'can be a url or a path'
    required: false
  conda-env-name:
    description: ''
    required: false
  conda-prefix:
    description: "Miniconda prefix, if it fails to run 'conda --version', will install one there"
    required: false
  conda-installer-url:
    description: 'If conda not installed, use this url to download installer'
    required: false
    default: 'https://repo.anaconda.com/miniconda/Miniconda3-py39_4.10.3-Linux-x86_64.sh'
  manylinux-cache-dir:
    description: 'path to store cache produced by manylinux build, cmake build dir, .ccache dir, python .local'
    required: true
  # Other args
  force-rebuild:
    description: 'rebuild even package with same key found'
    required: false
    default: false
  dry-run:
    description: ''
    required: false
    default: false
  self-hosted:
    description: ''
    required: false
    default: false
  python-versions:
    description: ''
    required: true
  wheelhouse-dir:
    description: 'where to put the produced .whl files'
    required: false
  clear-wheelhouse-dir:
    description: 'clear wheelhouse-dir'
    required: false
  wheel-audit:
    description: 'clear wheelhouse-dir'
    required: false
    default: true
  build-script:
    description: 'a bash script to build oneflow'
    required: true
  retry-failed-build:
    description: 'Retry a failed build oneflow or not'
    required: false
    default: false
  clean-ccache:
    description: ''
    required: false
    default: false
  docker-run-use-system-http-proxy:
    description: ''
    required: false
    default: false
  docker-run-use-lld:
    description: ''
    required: false
    default: false
  ssh-tank-host:
    description: ''
    required: false
    default: false
  ssh-tank-path:
    description: ''
    required: false
    default: '/tank'
  ssh-tank-base-url:
    description: ''
    required: true
  parallel:
    description: 'make/ninja -j {parallel}, default will be $(nproc)'
    required: false
  nightly:
    description: 'is nightly build, note this is not a boolean filed, any none empty string will be considered as true'
    required: false

outputs:
  pip-index-url:
    description: 'pip index url could be use to install oneflow'
runs:
  using: 'node12'
  main: 'dist/index.js'
