name: "Build/Get OneFlow"
description: ""
inputs:
  # OneFlow args
  oneflow-build-env:
    description: "environment to build OneFlow: conda, manylinux"
    required: true
  oneflow-src:
    description: "path to OneFlow source code"
    required: true
  oneflow-build-key:
    description: "the key to check if two builds are equivalent to each other, usually is hash value of non-test cpp and python files"
    required: true
    default: "none"
  # CMake args
  cmake-init-cache:
    description: "path to CMake initial cache file to build OneFlow"
    required: true
  # Cuda args
  cuda-version:
    description: "default is none, format: 10.1, 10.2"
    required: false
    default: "none"
  # Conda args
  conda-env-file:
    description: ""
    required: true
  # Other args
  force-rebuild:
    description: "rebuild even package with same key found"
    required: false
    default: "false"
  dry-run:
    description: ""
    required: false
    default: "false"
outputs:
  pip-index-url:
    description: "pip index url could be use to install oneflow"
runs:
  using: "node12"
  main: "../dist/index.js"
