name: 'Upload by digest'
description: ''
inputs:
  entry:
    description: ''
    required: true
  digest:
    description: ''
    required: true
  ssh-tank-host:
    description: ''
    required: false
  ssh-tank-path:
    description: ''
    required: false
    default: '/tank'

outputs:
  runs-on:
    description: 'if cache found, will generate a [ubuntu-latest], in JSON'
  build-cache-hit:
    description: ''
  test-cache-hit:
    description: ''
  build-digest:
    description: ''
  test-digest:
    description: ''

runs:
  using: 'node12'
  main: '../../dist/uploadByDigest/index.js'
branding:
  icon: 'archive'
  color: 'gray-dark'
