name: 'Upload by digest'
description: ''
inputs:
  entry:
    description: ''
    required: true
  digest:
    description: ''
    required: true
  ssh-tank-host:
    description: ''
    required: false
  ssh-tank-path:
    description: ''
    required: false
    default: '/tank'

runs:
  using: 'node12'
  main: '../../dist/uploadByDigest/index.js'
branding:
  icon: 'archive'
  color: 'gray-dark'
