name: "Revive PRs"
description: ""
inputs:
  action-type:
    description: ""
    required: false
    default: "revive-pr"
  token:
    required: true
    description: ""

runs:
  using: "node12"
  main: "../dist/index.js"
branding:
  icon: "archive"
  color: "gray-dark"
