name: "Find oneflow wheel in oss"
description: ""
inputs:
  action-type:
    description: ""
    required: false
    default: "master-address"
  rank:
    required: true
    description: ""
outputs:
  master-address:
    description: ""

runs:
  using: "node20"
  main: "../dist/index.js"
branding:
  icon: "archive"
  color: "gray-dark"
