name: "Revive PRs"
description: ""
inputs:
  action-type:
    description: ""
    required: false
    default: "pytest-benchmark"
  container-name:
    required: true
    description: ""
  pytest-script:
    required: true
    description: ""
  benchmark-id:
    required: true
    description: ""
  pytest-args:
    required: true
    description: ""
  collect-path:
    required: true
    description: ""
  unknown-threshold:
    required: true
    description: ""
  error-threshold:
    required: true
    description: ""

runs:
  using: "node20"
  main: "../dist/index.js"
branding:
  icon: "archive"
  color: "gray-dark"
