name: 'Build/Get OneFlow'
description: ''
inputs:
  action-type:
    description: ''
    required: false
    default: 'performance/speed'
  pytorch-run:
    description: ''
    required: false
    default: ''
  oneflow-run:
    description: ''
    required: false
    default: 'false'


outputs:
  pip-index-url:
    description: 'pip index url could be use to install oneflow'
runs:
  using: 'node12'
  main: '../dist/index.js'
