name: "Check PR priority"
description: ""
inputs:
  action-type:
    description: ""
    required: false
    default: "priority-pr"
  token:
    required: true
    description: ""

runs:
  using: "node20"
  main: "../dist/index.js"
branding:
  icon: "archive"
  color: "gray-dark"
