name: 'Find oneflow wheel in oss'
description: ''
inputs:
  action-type:
    description: ''
    required: false
    default: 'find-wheel'
  ref:
    required: true
    description: 'oneflow commit id'  
  entry:
    required: true
    description: 'compute platform entry, e.g. cu112'
  python-version:
    required: true
    description: 'python version'
outputs:
  find-wheel-hit:
    description: ''

runs:
  using: 'node12'
  main: '../dist/index.js'
branding:
  icon: 'archive'
  color: 'gray-dark'
