name: 'Build/Get OneFlow'
description: ''
inputs:
  oneflow-src:
    description: 'path to OneFlow source code'
    required: true
  entry:
    description: 'entry to cache completion status'
    required: true
  runner-labels:
    required: false
    description: 'runner labels to output if cache not found'
  mark-as-completed:
    required: false
    description: 'if true, will mark keys as completed when this job is success'
    default: false
  digest-type:
    required: true
    description: 'build|test'
outputs:
  runs-on:
    description: 'if cache found, will generate a [ubuntu-latest], in JSON'
  build-cache-hit:
    description: ''
  test-cache-hit:
    description: ''
  build-digest:
    description: ''
  test-digest:
    description: ''

runs:
  using: 'node12'
  main: '../dist/index.js'
  post: '../dist/index.js'
  post-if: success()
branding:
  icon: 'archive'
  color: 'gray-dark'
