name: 'Upload by digest'
description: ''
inputs:
  action-type:
    description: ''
    required: false
    default: 'digest/upload'
  src-dir:
    description: 'path to OneFlow source code'
    required: true
  dst-dir:
    description: 'path to OneFlow source code'
    required: true
  entry:
    description: ''
    required: true
  digest:
    description: ''
    required: true
  ssh-tank-host:
    description: ''
    required: false
  ssh-tank-path:
    description: ''
    required: false
    default: '/tank'
  pr_sym_link:
    description: 'create symbol link after updload'
    required: false

runs:
  using: 'node12'
  main: '../../dist/index.js'
branding:
  icon: 'archive'
  color: 'gray-dark'
