name: scp files
on: [push]
env:
  SSH_TANK_HOST: 192.168.1.23
  SSH_TANK_PATH: /home/ci-user/tank
jobs:

  build:
    name: Build
    runs-on: ['self-hosted', 'linux', 'provision']
    steps:
    - run: touch test.txt
    - name: cp
      run: |
        echo "SSH_KEY=$(cat ~/.ssh/id_rsa)" >> $GITHUB_ENV
    - name: Upload whl
      uses: appleboy/scp-action@master
      with:
        host: ${{ env.SSH_TANK_HOST }}
        source: 'test.txt'
        key: ${{ env.SSH_KEY }}
        target: '${{ env.SSH_TANK_PATH }}/test-dir'
        rm: true
