name: scp files
on: [push]
env:
  SSH_TANK_HOST: 192.168.1.23
  SSH_TANK_PATH: /home/ci-user/tank
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: touch test.txt
    - name: Upload whl
      uses: appleboy/scp-action@master
      with:
        host: ${{ env.SSH_TANK_HOST }}
        source: 'test.txt'
        key_path: /home/ci-user/.ssh/id_rsa
        target: '${{ env.SSH_TANK_PATH }}/test-dir'
