name: 'Find oneflow wheel in oss'
description: ''
inputs:
  action-type:
    description: ''
    required: false
    default: 'wait-for-gpu'
  max-try-times:
    required: true
    description: ''
  timeout-minutes:
    required: true
    description: ''
  token:
    required: true
    description: ''

runs:
  using: 'node12'
  main: '../dist/index.js'
branding:
  icon: 'archive'
  color: 'gray-dark'
